Ruse2023/Ruse2023/Controllers/ModeratorController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Ruse2023.Models.Moderator;
using Ruse2023.Services.AccountService;
using Ruse2023.Services.ModeratorService;

namespace Ruse2023.Controllers
{
    public class ModeratorController : Controller
    {
        private readonly IAccountService accountService;
        private readonly IModeratorService moderatorService;
        public ModeratorController(IAccountService accountService,
                                   IModeratorService moderatorService)
        {
            this.accountService = accountService;
            this.moderatorService = moderatorService;
        }
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Apply()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Apply(ApplicationModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var result = await moderatorService.ApplyPost(accountService.GetUserId(), model);

            if (!result)
            {
                return RedirectToAction("Error", "Home");
            }

            return RedirectToAction("Index", "Home");
        }
        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            return View(await moderatorService.GetDetails(id));
        }

        [HttpGet]
        public async Task<IActionResult> Approve(int id)
        {
            var result = await moderatorService.Approve(id);

            if (!result) return RedirectToAction("Error", "Home");

            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public async Task<IActionResult> Decline(int id)
        {
            return View(new ApplicationDeclineModel() { Id = id });
        }

        [HttpPost]
        public async Task<IActionResult> Decline(ApplicationDeclineModel model)
        {
            if (!ModelState.IsValid) return View(model);

            await moderatorService.Decline(model);

            return RedirectToAction("Index", "Home");
        }
        [Authorize]
        public async Task<IActionResult> MyApplications()
        {
            return View(await moderatorService.GetMyApplications(accountService.GetUserId()));
        }
        [Authorize]
        public async Task<IActionResult> ApplicationDetails(int id)
        {
            return View(await moderatorService.GetDetails(id));
        }
    }
}

Ruse2023/Ruse2023/Controllers/StoreController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Ruse2023.Data;
using Ruse2023.Data.Models;
using Ruse2023.Models;
using Ruse2023.Models.Store;
using Ruse2023.Services.AccountService;
using Ruse2023.Services.StoreService;

namespace Ruse2023.Controllers
{
    public class StoreController : Controller
    {
        private readonly IStoreService storeService;
        private readonly IAccountService accountService;
        private readonly ApplicationDbContext context;
        public StoreController(IStoreService storeService,
                               IAccountService accountService,
                               ApplicationDbContext context)
        {
            this.storeService = storeService;
            this.context = context;
            this.accountService = accountService;
        }
        public async Task<IActionResult> Index()
        {
            var credits = await context.Credits.FirstOrDefaultAsync(x => x.UserId == accountService.GetUserId());

            if (credits == null)
            {
                var c = new Credits()
                {
                    UserId = accountService.GetUserId(),
                    Ammount = 0
                };

                await context.Credits.AddAsync(c);
                await context.SaveChangesAsync();
            }

            return View(new StoreModel(){
                Products = await storeService.GetAllProducts(), Credits = context.Credits.FirstOrDefaultAsync(x => x.UserId == accountService.GetUserId()).Result.Ammount
            });
        }
        [Authorize(Policy = "AdministratorModeratorPolicy")]
        public IActionResult AddProduct()
        {
            return View();
        }
        [HttpPost]
        [Authorize(Policy = "AdministratorModeratorPolicy")]
        public async Task<IActionResult> AddProduct(ProductModel model, List<IFormFile> Image)
        {
            if (!ModelState.IsValid && model.Image != null)
            {
                return View(model);
            }

            var res = await storeService.AddProduct(model, Image);

            if (!res) return Unauthorized();

            return RedirectToAction("Index", "Home");
        }
        [Authorize]
        public async Task<IActionResult> ProductById(int id)
        {
            return View(await storeService.ProductById(id));
        }
        [Authorize]
        public async Task<IActionResult> BuyProduct(int id)
        {
            var result = await storeService.BuyProduct(id, accountService.GetUserId());

            if (!result) return Unauthorized();

            return RedirectToAction("Index", "Home");
        }
    }
}

Ruse2023/Ruse2023/Views/Moderator/Apply.cshtml
@{
	Layout = "";
}@using Ruse2023.Models.Moderator;
@model ApplicationModel

<head>
    <meta charset="UTF-8">
    <title>CodePen - Contact Us</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://demo.voidcoders.com/htmldemo/fitgear/main-files/assets/css/animate.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/treeplantCss.css">
    <link rel="stylesheet" href="~/assets/css/main.css" />
    <link rel="stylesheet" href="css/treeplant.css" />
    <noscript><link rel="stylesheet" href="assets/css/noscript.css" /></noscript>
</head>

<script src="~/assets/js/jquery.min.js"></script>
<script src="~/assets/js/jquery.scrollex.min.js"></script>
<script src="~/assets/js/jquery.scrolly.min.js"></script>
<script src="~/assets/js/browser.min.js"></script>
<script src="~/assets/js/breakpoints.min.js"></script>
<script src="~/assets/js/util.js"></script>
<script src="~/assets/js/main.js"></script>

<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

	<title>Booking Form HTML Template</title>

	<!-- Google font -->
	<link href="http://fonts.googleapis.com/css?family=Playfair+Display:900" rel="stylesheet" type="text/css" />
	<link href="http://fonts.googleapis.com/css?family=Alice:400,700" rel="stylesheet" type="text/css" />

	<!-- Bootstrap -->
	<link type="text/css" rel="stylesheet" href="css/bootstrap.min.css" />

	<!-- Custom stlylesheet -->
	<link type="text/css" rel="stylesheet" href="css/style.css" />

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->

</head>

<body>
	<div id="booking" class="section">
		<div class="section-center">
			<div class="container">
				<div class="row">
					<div class="booking-form">
						<div class="booking-bg">
							<div class="form-header">
								<h2>Make your reservation</h2>
								<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate laboriosam numquam at</p>
							</div>
						</div>
						<form id="account" method="post">
							<div class="row">
								<div class="col-md-6">
									<div class="form-group" id="asd">
										<label asp-for="Description"></label>
										<textarea asp-for="Description" id="asdd" class="form-control"></textarea>
    									<span asp-validation-for="Description" class="text-danger"></span>
									</div>
								</div>
							</div>
							<div class="form-btn">
								<button type="submit" class="submit-btn">Submit</button>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</body><!-- This templates was made by Colorlib (https://colorlib.com) -->

</html>

<style>
    .section {
	position: relative;
	height: 100vh;
}
#asd{
		height: 200px;
		font-size: 14pt;
	}

	#asdd {
		height: 100px;
		width:300px;
		font-size: 14pt;
	}

.section .section-center {
	position: absolute;
	top: 50%;
	left: 0;
	right: 0;
	-webkit-transform: translateY(-50%);
	transform: translateY(-50%);
}

#booking {
	font-family: 'Alice', serif;
}

.booking-form {
	position: relative;
	max-width: 912px;
	width: 100%;
	margin: auto;
	background: #fff;
	border-radius: 6px;
	-webkit-box-shadow: 0px 5px 10px -5px rgba(0, 0, 0, 0.1);
	box-shadow: 0px 5px 10px -5px rgba(0, 0, 0, 0.1);
}

.booking-form .booking-bg {
	position: absolute;
	left: 25px;
	top: -25px;
	bottom: -25px;
	width: 400px;
	background-image: url('../img/background.jpg');
	background-size: cover;
	background-position: center;
	padding: 25px;
	border-radius: 6px;
	-webkit-box-shadow: 0px 5px 10px -5px rgba(0, 0, 0, 0.1);
	box-shadow: 0px 5px 10px -5px rgba(0, 0, 0, 0.1);
	overflow: hidden;
}

.booking-form .booking-bg::before {
	content: '';
	position: absolute;
	left: 0;
	right: 0;
	bottom: 0;
	top: 0;
	background: green;
}

.booking-form>form {
	margin-left: 425px;
	padding: 30px;
}

.booking-form .form-header {
	margin-bottom: 30px;
	margin-top: 60px;
	position: relative;
	z-index: 20;
}

.booking-form .form-header h2 {
	font-family: 'Playfair Display', serif;
	margin-top: 0;
	margin-bottom: 15px;
	font-weight: 900;
	color: #fff;
	font-size: 42px;
	text-transform: capitalize;
}

.booking-form .form-header p {
	color: #fff;
	font-size: 18px;
}

.booking-form .form-group {
	position: relative;
	margin-bottom: 20px;
}

.booking-form .form-control {
	background-color: #fff;
	height: 45px;
	padding: 0px 15px;
	color: #151515;
	border: 1px solid #e5e5e5;
	font-size: 16px;
	font-weight: 700;
	-webkit-box-shadow: none;
	box-shadow: none;
	border-radius: 40px;
	-webkit-transition: 0.2s all;
	transition: 0.2s all;
}

.booking-form .form-control::-webkit-input-placeholder {
	color: #e5e5e5;
}

.booking-form .form-control:-ms-input-placeholder {
	color: #e5e5e5;
}

.booking-form .form-control::placeholder {
	color: #e5e5e5;
}

.booking-form .form-control:focus {
	background: #f8f8f8;
}

.booking-form input[type="date"].form-control:invalid {
	color: #e5e5e5;
}

.booking-form select.form-control {
	-webkit-appearance: none;
	-moz-appearance: none;
	appearance: none;
}

.booking-form select.form-control:invalid {
	color: #e5e5e5;
}

.booking-form select.form-control option {
	color: #151515;
}

.booking-form select.form-control+.select-arrow {
	position: absolute;
	right: 3px;
	bottom: 5px;
	width: 32px;
	line-height: 32px;
	height: 32px;
	text-align: center;
	pointer-events: none;
	color: #e5e5e5;
	font-size: 14px;
}

.booking-form select.form-control+.select-arrow:after {
	content: '\279C';
	display: block;
	-webkit-transform: rotate(90deg);
	transform: rotate(90deg);
}

.booking-form .form-label {
	color: green;
	text-transform: uppercase;
	line-height: 24px;
	height: 24px;
	font-size: 14px;
	font-weight: 400;
	margin-left: 20px;
}

.booking-form .form-btn {
	margin-top: 30px;
}

.booking-form .submit-btn {
	display: block;
	width: 100%;
	color: #fff;
	background-color: green;
	font-weight: 700;
	font-size: 18px;
	border: none;
	border-radius: 40px;
	height: 55px;
	-webkit-transition: 0.2s all;
	transition: 0.2s all;
}

.booking-form .submit-btn:hover,
.booking-form .submit-btn:focus {
	background-color: lightgreen;
}


</style>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Ruse2023/Ruse2023/Views/Moderator/Decline.cshtml
@{
    Layout = "";
}@using Ruse2023.Models.Moderator;
@model ApplicationDeclineModel

<head>
    <meta charset="UTF-8">
    <title>CodePen - Contact Us</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://demo.voidcoders.com/htmldemo/fitgear/main-files/assets/css/animate.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/treeplantCss.css">
    <link rel="stylesheet" href="~/assets/css/main.css" />
    <link rel="stylesheet" href="css/treeplant.css" />
    <noscript><link rel="stylesheet" href="assets/css/noscript.css" /></noscript>
</head>

<script src="~/assets/js/jquery.min.js"></script>
<script src="~/assets/js/jquery.scrollex.min.js"></script>
<script src="~/assets/js/jquery.scrolly.min.js"></script>
<script src="~/assets/js/browser.min.js"></script>
<script src="~/assets/js/breakpoints.min.js"></script>
<script src="~/assets/js/util.js"></script>
<script src="~/assets/js/main.js"></script>

<form id="account" method="post">
    <label asp-for="@Model.Feedback"></label>
    <input asp-for="@Model.Feedback" class="form-control" />
    <span asp-validation-for="@Model.Feedback" class="text-danger"></span>
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <button type="submit" class="btn btn-warning">Decline</button>
    </div>
</form>

Ruse2023/Ruse2023/Views/Moderator/MyApplications.cshtml
@{
    Layout = "";
}@using Ruse2023.Models.Moderator;
@model IEnumerable<ApplicationApprovalModel>

<head>
    @*   <link rel="stylesheet" href="~/css/Buy.css" />*@

    <link rel="stylesheet" href="~/assets/css/main.css" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
    <noscript><link rel="stylesheet" href="~/assets/css/noscript.css" /></noscript>
</head>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Shop Homepage - Start Bootstrap Template</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="~/assets/favicon.ico" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="~/css/styles.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/assets/css/main.css" />
    <noscript><link rel="stylesheet" href="~/assets/css/noscript.css" /></noscript>
</head>
<body>
    <!-- Navigation-->
    <header id="header" class="alt">
        <h1><a href="index.html">EcoWay</a></h1>
        <nav id="nav">
            <ul>
                <li class="special">
                    <a href="#menu" class="menuToggle"><span>Menu</span></a>
                    <div id="menu">
                        <ul>
                            <li><a asp-action="Index" asp-controller="Home">Начало</a></li>
                            <li><a asp-action="Index" asp-controller="Store">Магазин</a></li>
                            @if (!User.Identity.IsAuthenticated)
                            {
                                <li><a asp-action="Register" asp-controller="Account">Регистриране</a></li>
                                <li><a asp-action="Login" asp-controller="Account">Вписване</a></li>
                            }
                            else
                            {
                                <li><a asp-action="Profile" asp-controller="Account">Акаунт</a></li>
                                <li><a asp-action="Logout" asp-controller="Account">Изход</a></li>
                            }
                        </ul>
                    </div>
                </li>
            </ul>
        </nav>
    </header>
    <!-- Header-->
    <header class="bg-dark py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">Вашите апликации за модератор</h1>
                <p class="lead fw-normal text-white-50 mb-0">Добре дошли!</p>
            </div>
        </div>
    </header>
    <!-- Section-->
    <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                @foreach (var product in Model)
                {
                    <div class="col mb-5">
                        <div class="card h-100">
                            <h2 style="color: black" class="card-body p-4">@product.FirstName @product.LastName</h2>
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <h5 class="fw-bolder" style="color: black;">@product.Description</h5>
                                    <div class="d-flex justify-content-center small text-warning mb-2">
                                    </div>
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" asp-action="ApplicationDetails" asp-controller="Moderator" asp-route-id="@product.Id">Детайли</a></div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </section>
    <!-- Footer-->
    <footer class="py-5 bg-dark">
        <div class="container"><p class="m-0 text-center text-white"></p></div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="~/js/scripts.js"></script>

    <script src="~/assets/js/jquery.min.js"></script>
    <script src="~/assets/js/jquery.scrollex.min.js"></script>
    <script src="~/assets/js/jquery.scrolly.min.js"></script>
    <script src="~/assets/js/browser.min.js"></script>
    <script src="~/assets/js/breakpoints.min.js"></script>
    <script src="~/assets/js/util.js"></script>
    <script src="~/assets/js/main.js"></script>
</body>

<style>
    .card-img,
    .card-img-top {
        width: 100%;
        height: 100%;
    }
</style>