Ruse2023/Ruse2023/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Ruse2023.Data;
using Ruse2023.Models;
using Ruse2023.Services.AccountService;
using Ruse2023.Services.ApiService;
using Ruse2023.Services.StoreService;
using System.Diagnostics;

namespace Ruse2023.Controllers
{
    public class HomeController : Controller
    {
        private readonly IStoreService storeService;
        private readonly IApiService apiService;
        private readonly IAccountService accountService;
        private readonly ApplicationDbContext context;
        public HomeController(IStoreService storeService,
                              IApiService apiService,
                              IAccountService accountService,
                              ApplicationDbContext context)
        {
            this.storeService = storeService;
            this.apiService = apiService;
            this.accountService = accountService;
            this.context = context;
        }
        public async Task<IActionResult> Index()
        {
            var ap = new ApplicationStatisticsModel()
            {
                Users = await context.Users.CountAsync(),
                CreditsRewarded = await context.Credits.SumAsync(x => x.Ammount) + await context.BoughtProducts.SumAsync(x => x.Product.Price),
                PlantedTrees = await context.TreePlantApplications.Where(x => x.Status == "Approved").CountAsync(),
                EcoShopping = await context.ShoppingApplications.Where(x => x.Status == "Approved").CountAsync(),
            };

            return View(new HomePageModel
            {
                Products = await apiService.GetTopProducts(),
                Users = await accountService.GetUsers(),
                Stats = ap
            });
        }
        public IActionResult AboutUs()
        {
            return View();
        }
        public IActionResult Contacts()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Ruse2023/Ruse2023/Controllers/ShoppingController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Ruse2023.Models.Shopping;
using Ruse2023.Services.AccountService;
using Ruse2023.Services.ShoppingService;

namespace Ruse2023.Controllers
{
    public class ShoppingController : Controller
    {
        private readonly IShoppingService shoppingService;
        private readonly IAccountService accountService;
        public ShoppingController(IShoppingService shoppingService,
                                  IAccountService accountService)
        {
            this.shoppingService = shoppingService;
            this.accountService = accountService;
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(ShoppingApplicationModel model, List<IFormFile> Image)
        {
            if (!ModelState.IsValid) return View(model);

            var result = await shoppingService.Create(model, Image, this.accountService.GetUserId());

            if (!result) return Unauthorized();

            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        [Authorize(Policy = "AdministratorModeratorPolicy")]
        public async Task<IActionResult> Applications()
        {
            return View(await shoppingService.GetAll());
        }

        [HttpGet]
        [Authorize(Policy = "AdministratorModeratorPolicy")]
        public async Task<IActionResult> Details(int id)
        {
            return View(await shoppingService.GetDetails(id));
        }

        [HttpPost]
        [Authorize(Policy = "AdministratorModeratorPolicy")]
        public async Task<IActionResult> Details(ShoppingApprovalModel model)
        {
            await shoppingService.GiveCredits(model);

            return RedirectToAction("Index", "Home");
        }

        [Authorize(Policy = "AdministratorModeratorPolicy")]
        public async Task<IActionResult> Decline(int id)
        {
            await shoppingService.Decline(id);

            return RedirectToAction("Index", "Home");
        }
        [Authorize]
        public async Task<IActionResult> MyApplications()
        {
            return View(await shoppingService.GetMyApplications(accountService.GetUserId()));
        }
        [Authorize]
        public async Task<IActionResult> ApplicationDetails(int id)
        {
            return View(await shoppingService.GetDetails(id));
        }
    }
}

Ruse2023/Ruse2023/Controllers/StoreController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Ruse2023.Data;
using Ruse2023.Data.Models;
using Ruse2023.Models;
using Ruse2023.Models.Store;
using Ruse2023.Services.AccountService;
using Ruse2023.Services.StoreService;

namespace Ruse2023.Controllers
{
    public class StoreController : Controller
    {
        private readonly IStoreService storeService;
        private readonly IAccountService accountService;
        private readonly ApplicationDbContext context;
        public StoreController(IStoreService storeService,
                               IAccountService accountService,
                               ApplicationDbContext context)
        {
            this.storeService = storeService;
            this.context = context;
            this.accountService = accountService;
        }
        public async Task<IActionResult> Index()
        {
            var credits = await context.Credits.FirstOrDefaultAsync(x => x.UserId == accountService.GetUserId());

            if (credits == null)
            {
                var c = new Credits()
                {
                    UserId = accountService.GetUserId(),
                    Ammount = 0
                };

                await context.Credits.AddAsync(c);
                await context.SaveChangesAsync();
            }

            return View(new StoreModel(){
                Products = await storeService.GetAllProducts(), Credits = context.Credits.FirstOrDefaultAsync(x => x.UserId == accountService.GetUserId()).Result.Ammount
            });
        }
        [Authorize(Policy = "AdministratorModeratorPolicy")]
        public IActionResult AddProduct()
        {
            return View();
        }
        [HttpPost]
        [Authorize(Policy = "AdministratorModeratorPolicy")]
        public async Task<IActionResult> AddProduct(ProductModel model, List<IFormFile> Image)
        {
            if (!ModelState.IsValid && model.Image != null)
            {
                return View(model);
            }

            var res = await storeService.AddProduct(model, Image);

            if (!res) return Unauthorized();

            return RedirectToAction("Index", "Home");
        }
        [Authorize]
        public async Task<IActionResult> ProductById(int id)
        {
            return View(await storeService.ProductById(id));
        }
        [Authorize]
        public async Task<IActionResult> BuyProduct(int id)
        {
            var result = await storeService.BuyProduct(id, accountService.GetUserId());

            if (!result) return Unauthorized();

            return RedirectToAction("Index", "Home");
        }
    }
}

Ruse2023/Ruse2023/Controllers/TreePlantController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Ruse2023.Models.TreePlant;
using Ruse2023.Services.AccountService;
using Ruse2023.Services.TreePlantService;

namespace Ruse2023.Controllers
{
    public class TreePlantController : Controller
    {
        private readonly ITreePlantService treePlantService;
        private readonly IAccountService accountService;
        public TreePlantController(ITreePlantService treePlantService,
                                   IAccountService accountService)
        {
            this.treePlantService = treePlantService;
            this.accountService = accountService;
        }
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(TreePlantApplicationModel model, List<IFormFile> Image)
        {
            if (!ModelState.IsValid) return View(model);

            var result = await treePlantService.CreateApplication(model, Image, accountService.GetUserId());

            if (!result) return RedirectToAction("Error", "Home");

            return RedirectToAction("Index", "Home");
        }
        [HttpGet]
        [Authorize(Policy = "AdministratorModeratorPolicy")]
        public async Task<IActionResult> Applications()
        {
            return View(await treePlantService.GetAll());
        }
        [HttpGet]
        [Authorize(Policy = "AdministratorModeratorPolicy")]
        public async Task<IActionResult> Details(int id)
        {
            return View(await treePlantService.GetDetails(id));
        }

        [HttpPost]
        [Authorize(Policy = "AdministratorModeratorPolicy")]
        public async Task<IActionResult> Details(TreePlantApprovalModel model)
        {
            await treePlantService.GiveCredits(model);

            return RedirectToAction("Index", "Home");
        }

        [Authorize(Policy = "AdministratorModeratorPolicy")]
        public async Task<IActionResult> Decline(int id)
        {
            await treePlantService.Decline(id);

            return RedirectToAction("Index", "Home");
        }
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> ApplicationDetails(int id)
        {
            return View(await treePlantService.GetDetails(id));
        }
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> MyApplications()
        {
            return View(await treePlantService.GetMyApplications(accountService.GetUserId()));
        }
    }
}

Ruse2023/Ruse2023/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    Layout = "";
}
@model HomePageModel

<html>
<head>
    <title>EcoWay</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <link rel="stylesheet" href="assets/css/main.css" />
    <link rel="stylesheet" href="css/treeplant.css" />
    <noscript><link rel="stylesheet" href="assets/css/noscript.css" /></noscript>
</head>
<body class="landing is-preload">

    <div id="logo">
        <img src="~/images/Screenshot_20231027_101853_Chrome-removebg.png" style="width: 70px; height:70px;" />
    </div>

    <!-- Page Wrapper -->
    <div id="page-wrapper">

        <!-- Header -->
        <header id="header" class="alt">
            <h1><a href="index.html">EcoWay</a></h1>
            <nav id="nav">
                <ul>
                    <li class="special">
                        <a href="#menu" class="menuToggle"><span>Menu</span></a>
                        <div id="menu">
                            <ul>
                                <li><a asp-controller="Home" asp-action="Index">Начало</a></li>
                                <li><a asp-action="Index" asp-controller="Store">Магазин</a></li>
                                @if (!User.Identity.IsAuthenticated)
                                {
                                    <li><a asp-action="Register" asp-controller="Account">Регистрация</a></li>
                                    <li><a asp-action="Login" asp-controller="Account">Вписване</a></li>
                                }
                                else
                                {
                                    <li><a asp-action="Profile" asp-controller="Account">Акаунт</a></li>
                                    <li><a asp-action="Logout" asp-controller="Account">Изход</a></li>   
                                }
                            </ul>
                        </div>
                    </li>
                </ul>
            </nav>
        </header>

        <!-- Banner -->
        <section id="banner">
            <div class="inner">
                <h2>EcoWay</h2>
                <p>
                    Започни<br />
                    промяната<br />
                    с EcoWay
                </p>
            </div>
            <a href="#two" class="more scrolly">Научи повече</a>
        </section>

        <!-- One -->
        <section id="one" class="wrapper style1 special">
            <div class="inner">
                <header class="major">
                    <h2>
                        Рециклирането по нов иновативен начин!<br>
                        Ние сме EcoWay!<br />
                        Тук сме за да помогнем на хората да започнат по-екологичен начин на живот.
                    </h2>
                    <p>
                        <br />

                    </p>
                </header>
                <ul class="icons major">
                    <li><span class="icon fa-map major style1"><span class="label">Lorem</span></span></li>
                    <li><span class="icon fa-heart major style2"><span class="label">Ipsum</span></span></li>
                    <li><span class="icon solid fa-shopping-cart major style3"><span class="label">Dolor</span></span></li>
                </ul>
            </div>
        </section>

        <!-- Two -->
        <section id="two" class="wrapper alt style2">
            <section class="spotlight">
            </section>
            <section class="spotlight">
                <div class="image"><img src="~/images/kolichka.jpg" alt="" /></div><div class="content">
                    <h2>
                        <a asp-action="Create" asp-controller="Shopping" class="button fit primary">Екологично пазаруване</a>
                        <br />

                    </h2>
                    <p>
                      Покажете ни вашите продукти с марка еко на тях<br> 
                         и получете награди за всеки един от тях!
                    </p>
                </div>
            </section>
            <section class="spotlight">
                <div class="image"><img src="images/pic03.jpg" alt="" /></div><div class="content">
                    <h2>
                        <a asp-action="Create" asp-controller="TreePlant" class="button fit primary">Засади дърво</a>
                        <br />
                    </h2>
                    <p>
                        Засадете дърво и помогнете за озенеляването на нашата планета.<br>
                        Всяко действие е от значение.<br />
                        Получавате награда за виште усилия!
                    </p>
                </div>
            </section>
        </section>

        <!-- Three -->
        <section id="three" class="wrapper style3 special">
            <div class="inner">

                <header class="major">
                    <h2></h2>
                    <p>
                        <br />

                    </p>
                </header>
                <ul class="features">
                    <li class="icon solid fa-user">
                        <p style="font-weight: bold" id="users">
                            @Model.Stats.Users потребителя  
                        </p>
                    </li>
                    <li class="icon solid fa-shopping-cart">
                        <p style="font-weight: bold">
                            @Model.Stats.EcoShopping еко покупки
                        </p>
                    </li>
                    <li class="icon solid fa-gift">
                        <p style="font-weight: bold">@Model.Stats.CreditsRewarded общо спечелени точки</p>
                    </li>
                    <li class="icon solid fa-globe">
                        <p style="font-weight: bold">@Model.Stats.PlantedTrees засадени дръвчета</p>
                    </li>
                    <li class="icon fa-heart">
                        <p style="font-weight: bold">7 официални спонсора</p>
                    </li>
                    <li class="icon fa-sun">
                        <p style="font-weight: bold">Вече сме в 8 държави</p>
                    </li>
                </ul>
            </div>
        </section>

        <!-- CTA -->
        <section id="cta" class="wrapper style4">
            <h1 style="display: flex; justify-content: center; align-items: center; font-size: 60px; font-weight: bold;">За нас</h1>
            <div class="inner">
                    
                    <p style="font-size: 20px;">
                        EcoWay е онлайн платформа, насочена към промотирането 
                        на еко осъзнатото поведение. Спонсориран от водещи екологични фондове, 
                        ние съчетаваме усилията за опазване на 
                        околната среда със социалната отговорност. 
                        Ние възнаграждаваме нашите потребители, 
                        които активно се ангажират с опазването на природата, 
                        като засаждат дървета и придобиват екологично устойчиви продукти. 
                        Със съвместни усилия търсим пътища за създаване на по-зелен и устойчив свят.

                    </p>
            </div>
        </section>

        <!-- Footer -->
        <footer id="footer">
            <ul class="icons">
                <h1 style="display: flex; justify-content: center; align-items: center; font-size: 30px; font-weight: bold;">Контакти</h1>
            </ul>
            Тел +3598888888; Имейл ecoway@gmail.com
        </footer>

    </div>

    <!-- Scripts -->
    <script src="assets/js/jquery.min.js"></script>
    <script src="assets/js/jquery.scrollex.min.js"></script>
    <script src="assets/js/jquery.scrolly.min.js"></script>
    <script src="assets/js/browser.min.js"></script>
    <script src="assets/js/breakpoints.min.js"></script>
    <script src="assets/js/util.js"></script>
    <script src="assets/js/main.js"></script>



</body>
</html>

<style>
    #id {
        text-align: center;
    }

    html {
        scroll-behavior: smooth;
    }

    .products {
        display: flex;
        flex-wrap: nowrap;
        justify-content: space-between;
        width: 92%;
    }

    #image {
        width: 50px;
        height: 90px;
    }

    #butona {
        width: 60%;
        height: 40px;
        font-size: 20px;
        display: flex; /* this enables the flexbox model */
        align-items: center; /* this vertically aligns the text in the middle */
        justify-content: center;
    }

    #form {
        border: 2px solid;
        border-radius: 25px;
        padding: 20px;
    }

    /* klient*/
    .klient {
        display: flex;
        flex-wrap: nowrap;
        justify-content: space-between;
        width: 92%;
    }

    #logo {
        position: absolute;
        top: 0;
        left: 0;
        width: 50px;
    }

    #snimkanaklient {
        width: 50px;
        height: 50px;
    }

    * {
        margin: 0;
        padding: 0;
    }

</style>

@section Scripts{
    <script>
        $.get('/api/getApplicationsStats', (data) => {
            $('#users').text(data.users);
            $('#plantedTrees').text(data.plantedTrees);
            $('#shopping').text(data.ecoShopping);
            $('#creditsRewarded').text(data.creditsRewarded);
            console.log(data.Success);
        });
    </script>
}